services:
  - type: web
    name: denguess-backend
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    plan: free

